### ISSUE TITLE
scrolling-content TODO

### ISSUE THREAD

**Issue by kkterai** [kkterai/InstaJam#2]
- [x] Implement styles for content scrolling
- [ ] Implement UI error messages in multi-content post fields
- [ ] Implement deletion of unused content fields
- [ ]  Update server-side validations to check multi-content vs. single element
